### ISSUE TITLE
Setting the font size of the sets

### ISSUE THREAD

**Issue by Pweidemueller** [gecko984/supervenn#18]
Hey, great package!

I'm struggeling to set the font size of the names of the sets displayed in the middle of the bars. I manage to access the axis to set the size of x and y label.

How can I access the other text elements to set their size?

**Comment by gecko984** [comment]
Hi! Thanks for your feedback. Hope you tapped that star on top of the page :-)
The `supervenn` function actually has a dedicated parameter named `fontsize`, but: 
1) I forgot to include it in the docstring 
2) I forgot to pass it to `side_plot()`

Both problems are fixed in the latest release 0.3.2, so you can upgrade and enjoy.
